name: freegram
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BLUETOOTH LIBRARIES CORRECTED FOR HYBRID STRATEGY ---
  flutter_blue_plus: ^1.31.18
  flutter_ble_peripheral: ^1.1.0
  vibration: ^3.1.4
  flutter_local_notifications: ^17.0.0
  # --- END BLUETOOTH UPDATE ---

  device_info_plus: ^9.1.2
  hive_generator: ^2.0.0 # Use the latest version
  build_runner: ^2.4.0   # Use the latest version

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.15
  firebase_database: ^10.4.5

  # Social Sign-In
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.4

  # Dependency Injection
  get_it: ^7.6.7

  # UI & UX
  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  shimmer: ^3.0.0
  card_swiper: ^3.0.1
  showcaseview: ^2.0.3
  country_picker: ^2.0.26
  simple_animations: ^5.0.2

  # Video
  video_player: ^2.8.6
  chewie: ^1.7.5
  video_editor: ^3.0.0
  video_compress: ^3.1.2
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  ffmpeg_kit_flutter_new: ^3.2.0

  # Utils
  http: ^1.1.0
  image_picker: ^1.0.7
  timeago: ^3.6.1
  uuid: ^4.2.2
  path_provider: ^2.1.2
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  google_fonts: ^6.2.1
  intl: ^0.18.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Permissions & Settings
  permission_handler: ^11.3.0
  app_settings: ^5.1.1
  qr_flutter: ^4.1.0

  # Store & Monetization
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  faker: ^2.1.0

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/music/
    - assets/fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf